import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from "@clerk/ui/themes";
import "./globals.css";
import Footer from "@/components/common/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable:"--font-montserrat",
  weight:["400","500","600","700","800","900"]
})

export const metadata: Metadata = {
  title: "AutoMat - Executive Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${montserrat.className}`}>
        <ClerkProvider
          appearance={{
            theme: shadcn,
            variables: {
              fontFamily: "var(--font-montserrat), var(--font-geist-sans)",
            },
          }}
        >
          {children}
          <Footer></Footer>
        </ClerkProvider>
      </body>
    </html>
  );
}
